FROM node:12.16-alpine as builder

WORKDIR /app

COPY . .

RUN yarn --frozen-lockfile --ignore-optional

RUN yarn build

FROM node:12.16.0-alpine

WORKDIR /app

COPY package.json ./

COPY yarn.lock .

RUN yarn --production=true --frozen-lockfile --ignore-optional

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/migrations ./migrations
COPY --from=builder /app/migrate-mongo-config.js ./

EXPOSE 3000

CMD ["yarn", "start:prod"]
